### ISSUE TITLE
Please update the qlmarkdown-gfm.rb for a new tap

### ISSUE THREAD

**Issue by BingoKingo** [Watson1978/QLMarkdownGFM#12]
Error: Non-checksummed download of qlmarkdown-gfm formula file from an arbitrary URL is unsupported! `brew extract` or `brew create` and `brew tap-new` to create a formula file in a tap on GitHub instead.

**Comment by Watson1978** [comment]
Your issue should be solved with https://github.com/Watson1978/QLMarkdownGFM/commit/56b707bd425f45c2104b3f24ea7fb9cda2364bfd
