### ISSUE TITLE
Doesn't work on High Sierra

### ISSUE THREAD

**Issue by ZhiliangWu** [Watson1978/QLMarkdownGFM#3]
on 10.13.6, tried to copy the file, either in `~/Library/Quicklook` and `/Library/Quicklook`. Doesn't seem to work with quicklook. (`qlmanage -r` given and even restarted the Mac)

**Comment by Watson1978** [comment]
Thank you for your report and sorry late reply.
Seems that I need more information to solve your issue about your machine specs, etc.

If you have been used other QuickLook plugin, could you remove them at first?

**Comment by christopheranderton** [comment]
Confirmed working on both macOS 10.13.x High Sierra and macOS 10.14.x Mojave. Like @Watson1978 wrote, try to remove any `.qlgenerator` plug-ins temporarily in:
```
/Library/QuickLook/  (except iWork.qlgenerator and iBooksAuthor.qlgenerator, as they are from Apple) and if any in:
~/Library/QuickLook/
```
And then restart (shouldn't be neccessary, but there is a bug in the macOS QuickLook Server that sometimes requires a restart). Then do `qlmanage -r` or `qlmanage -r cache && qlmanage -r` . If it works, try to add the removed `.qlgenerator` plug-ins one after one (and do a `qlmanage -r` everytime).

If you have `MultiMarkdown QuickLook.qlgenerator` or `QLMarkdown.qlgenerator` installed, they are most likely the culprits.  

You can also run `qlmanage -m plugins` which lists active qlplugins. Note that most plug-ins are listed inside app bundles and not in `~/Library/QuickLook/` or `/Library/QuickLook/` However the qlplugins installed by the user should take precedence.
